### ISSUE TITLE
Unable to close sarama.AsyncProducer

### ISSUE THREAD

**Issue by linfn** [tracer0tong/kafkalogrus#2]
The sarama.AsyncProducer needs to Close

**Comment by tracer0tong** [comment]
@llife09 if this is bug report, it's quite short. Logrus hook interface doesn't have special "Close" method. And in theory only one hook should be created per one hook assignment. So, in general, only one or several required amount of objects will be created, it will save from resource leakage. But graceful producer termination seems difficult for realization here.
